export const GET_CITY ='GET_CITY';
export const GET_ITINERARY = 'GET_ITINERARY';
export const GET_COMMENT ='GET_COMMENT';
export const GET_COMMENTID = 'GET_COMMENTID';
export const POST_COMMENT = 'POST_COMMENT';
export const GET_FAVOURITES='GET_FAVOURITES';
export const POST_FAVOURITES='POST_FAVOURITES';
export const DELETE_FAVOURITES='DELETE_FAVOURITES';